extends@: default

rules:
  slug:
    pattern: '[a-z][a-z0-9_\-]+'
    min: 2
    max: 80

form:
  fields:
    tabs:
      fields:
        # The Hypertext Tab is where everything else goes.
        hypertext:
          type: tab
          title: Hypertext
          fields:
            tabs:
              type: tabs
              classes: plain
              fields:
                content:
                  type: tab
                  title: Content
                  fields:
                    title:
                      type: text
                      label: Title
                    content:
                      type: textarea
                      label: Content
                settings:
                  type: tab
                  title: Settings
                  fields:
                    published:
                      type: toggle
                      label: Published
                    featured:
                      type: toggle
                      label: Featured
            columns:
              type: columns
              fields:
                overrides_column:
                  type: column
                  fields:
                    overrides_title:
                      type: section
                      title: JS/CSS Overrides
                      underline: true
                      import@:
                        type: css_js
                        context: theme://blueprints/partials
                    page_defaults_title:
                      type: section
                      title: Page Rendering Overrides
                      underline: true
                      import@:
                        type: page_defaults
                        context: theme://blueprints/partials
                content_column:
                  type: column
                  title: Extra Content & Metadata
                  fields:
                    content:
                      type: section
                      title: Extra Content
                      underline: true
                      import@:
                        type: extra_content
                        context: theme://blueprints/default-partials
                      