extends@: default

rules:
  slug:
    pattern: "[a-z][a-z0-9_\-]+"
    min: 2
    max: 80

form:
  fields:
    tabs:
      fields:        
        # The Hypertext Tab is where everything else goes.
        hypertext:
          type: tab
          title: Hypertext
          fields:
            columns:
              type: columns
              fields:
                overrides_column:
                  type: column
                  fields:
                    overrides_title:
                      type: section
                      title: JS/CSS Overrides
                      underline: true                      
                    header.allowCSS:
                      type: select
                      label: Allow CSS Override
                      help: Allow CSS only for this page, overriding any global settings.
                      classes: fancy
                      options:
                        default: Use global setting
                        enabled: Allow CSS
                        disabled: Block CSS
                    header.allowJS:
                      type: select
                      label: Allow JS Override
                      help: Allow JS only for this page, overriding any global settings.
                      classes: fancy
                      options:
                        default: Use global setting
                        enabled: Allow JS
                        disabled: Block JS
                    header.customCSS:
                      type: textarea
                      label: Custom CSS
                      size: large
                      help: Add your page-specific, custom CSS rules here.
                      placeholder: "e.g. table { font-family: Courier }"
                content_column:
                  type: column
                  title: Extra Content & Metadata
                  fields:
                    content:
                      type: section
                      title: Extra Content
                      underline: true

                    header.subtitle:
                      type: text
                      label: Subtitle
                      help: A subtitle to display under the title of a page.
                      style: fancy

                    header.show_header_image:
                      type: toggle
                      label: Show header image
                      help: When enabled, the header image will be shown at the top of this page.  If you don't specify one, the first image will be shown.
                      default: 0
                      highlight: 1
                      options:
                        1: Enabled
                        0: Disabled
                      validate:
                        type: bool
                    header.header_image_file:
                      type: text
                      toggleable: true
                      label: Header image file
                      help: Image filename that exists in the page folder to be shown at the top of this page. If not provided, and header image is enabled, Hypertext will use the first image found.
                      placeholder: my_image.jpg
                    header.thumbnail_image_file:
                      type: text
                      toggleable: true
                      label: Thumbnail image file
                      help: Image filename that exists in the page folder. If not provided, the header image will be used if possible.
                      placeholder: my_thumbnail.jpg

                    header.summary.delimiter:
                      type: text
                      help: A delimiter to use between the page summary and the rest of its contents. Anything above this delimiter will be used as the page summary, shown in any collections this page is a part of.
                      toggleable: true
                      label: Summary delimiter
                      classes: large
                      default: ===
                    header.summary.length:
                      type: text
                      help: The amount of text to take from the beginning of this page *if* you don't use the summary delimiter.
                      toggleable: true
                      label: Summary Length
                      classes: large
                      placeholder: 300
                      validate:
                        type: int
                        min: 1
                    
                    header.show_clickthrough:
                      type: toggle
                      label: Add `Continue Reading` link
                      help: When disabled, this page will not render a link to read more content in this page after the snippet.
                      default: 1
                      highlight: 1
                      options:
                        1: Enabled
                        0: Disabled
                      validate:
                        type: bool
